apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-queue-app
spec:
  replicas: 2  # Different replicas for different environments
  template:
    spec:
      containers:
        - name: azure-queue-app
          image: muntashir/azure-storage-queue:latest